### ISSUE TITLE
remove tracking URL from gmx webmail

### ISSUE THREAD

**Issue by tseeling** [trockerapp/trocker#17]
GMX is a german-language webmail provider (e.g. gmx.de, gmx.net, gmx.ch, gmx.at) and injects tracking URLs with a "derefer" function so they can spy on every URL you click in webmail.
A tracked URL looks like this (with spaces to defuse it):

https : // deref-gmx . net/mail/client/FkzI1_DoHKg/dereferrer/?redirectUrl=https %3A %2F %2F www . linuxfromscratch . org %2F hints%2Fdownloads%2Ffiles%2Flfs-uefi.txt

Is Trocker able to remove this kind of tracking?

**Comment by trockerapp** [comment]
Yes, we can add that to the [Trocker block list for tracked links](https://github.com/trockerapp/trocker/blob/2f3d2cea9c99f663d4f864e6dfdd530a350a2f64/chrome/lists.js#L108). Please send trockerapp@gmail.com a few test emails from that service so that we can validate the general url pattern of the deferrer.

**Comment by tseeling** [comment]
> 
> 
> Yes, we can add that to the [Trocker block list for tracked links](https://github.com/trockerapp/trocker/blob/2f3d2cea9c99f663d4f864e6dfdd530a350a2f64/chrome/lists.js#L108). Please send [trockerapp@gmail.com](mailto:trockerapp@gmail.com) a few test emails from that service so that we can validate the general url pattern of the deferrer.

The URLs are only added while reading emails in GMX's webinterface. They are not in any forwarded emails. I can collect some URLs from the web GUI and send them if this is ok as well.
